[workspace]
resolver = "2"
members = [
    "crates/f",
]

[workspace.package]
version = "0.1.1"
edition = "2024"
authors = ["David Beesley"]
license = "MIT"
repository = "https://github.com/davidbeesley/f"

[workspace.dependencies]
anyhow = "1"
env_logger = "0.11"
log = "0.4"
